language: go
go: 
    - 1.6.2

env:

before_install:
    - sudo pip install --user codecov
    
script:
    - go test -coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
